# Generated by Django 3.0.6 on 2020-05-29 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('data_morte', models.DateField(blank=True, null=True, verbose_name='Morto')),
            ],
            options={
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Inserisci il genere (es: fantascienza)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('sommario', models.TextField(help_text='Inserisci una breve descrizione del libro.', max_length=1000)),
                ('isbn', models.CharField(help_text='13 caratteri <a href="https://www.isbn-international.org/content/what-isbn"> ISBN </a>', max_length=13, verbose_name='ISBN')),
                ('autore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Autore')),
                ('genere', models.ManyToManyField(help_text='Scegli il genere per questo libro.', to='catalog.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='Istanza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID univoco di uno specifico libro nella biblioteca.', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('riconsegna', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(blank=True, choices=[('m', 'Manutenzione'), ('p', 'Prestato'), ('d', 'Disponibile'), ('r', 'Riservato')], default='m', help_text='Disponibilità del libro', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Libro')),
            ],
            options={
                'ordering': ['riconsegna'],
            },
        ),
    ]
