# Generated by Django 3.0.6 on 2020-06-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_lingua'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='lingua',
            field=models.ForeignKey(help_text='Lingua', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Lingua'),
        ),
    ]
