# Generated by Django 3.0.6 on 2020-06-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_libro_lingua'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titolo']},
        ),
        migrations.AlterField(
            model_name='istanza',
            name='imprint',
            field=models.CharField(help_text='Non so cosa sia in effetti...', max_length=200),
        ),
    ]
